import '../_globals.scss';
import { Jost } from 'next/font/google';
const urbanist = Jost({ subsets: ['latin'] });

import { ReduxProviders } from './redux-provider';

import '@/lib/firebase';

import { NavBar } from '@/components/NavBar/NavBar';

export const metadata = {
  title: 'ShelfX',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {
    icon: '/favicon.ico',
  },
  viewport: {
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={urbanist.className}>
        <ReduxProviders
          className="font-300 min-w-screen
        flex min-h-screen 
        flex-col-reverse text-lg  
        lg:flex-row lg:justify-between"
        >
          <NavBar />
          <main
            className="
          flex w-full  
          flex-col px-5  
          lg:py-8"
          >
            {children}
          </main>
        </ReduxProviders>
      </body>
    </html>
  );
}
