import "./_globals.scss";
import { Urbanist } from "next/font/google";
const urbanist = Urbanist({ subsets: ["latin"] });

import { Metadata } from "next";
import { Providers } from "./providers";

import "@/lib/firebase";

import { NavBar } from "@/components/NavBar/NavBar";

export const metadata: Metadata = {
  title: "ShelfX",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: {
    icon: "/favicon.ico",
  },
  viewport: {
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body
        className={`${urbanist.className} 
        text-lg font-300
        min-w-screen flex 
        min-h-screen flex-col-reverse  
        lg:flex-row lg:justify-between`}
      >
        <Providers>
          <NavBar />
          <main
            className="
          px-5 lg:py-8 lg:pr-8 
          flex flex-col  
          w-full"
          >
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
