import { Metadata } from "next";
import { AuthContextProvider } from "@/context/AuthContext";

import "./globals.scss";
import { Inter } from "next/font/google";

import Aside from "../components/Aside/Aside";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ShelfX",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body
        className={`${inter.className} 
        min-w-screen flex 
        min-h-screen flex-col-reverse  
        lg:flex-row lg:justify-between`}
      >
        <AuthContextProvider>
          <Aside />
          <main
            className="
          flex basis-full pr-0
          lg:py-8 lg:pr-8"
          >
            <div
              className="root 
              flex min-h-[100vh-91px] 
              w-full basis-full 
              bg-darkD-200  
              lg:rounded-xl lg:border-darkD-200"
            >
              {children}
            </div>
          </main>
        </AuthContextProvider>
      </body>
    </html>
  );
}
